# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  arduino:
    name: Arduino
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - core: esp32:esp32
            board: esp32:esp32:esp32
            index_url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
          - core: esp32:esp32
            board: esp32:esp32:esp32
            index_url: https://espressif.github.io/arduino-esp32/package_esp32_dev_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update

      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

      - name: Update core index
        run: arduino-cli core update-index --additional-urls "${{ matrix.index_url }}"

      - name: Install core
        run: arduino-cli core install --additional-urls "${{ matrix.index_url }}" ${{ matrix.core }}

      - name: Install Async TCP
        run: ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true arduino-cli lib install --git-url https://github.com/mathieucarbou/AsyncTCP#v3.1.2

      - name: Install ESP Async WebServer
        run: ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true arduino-cli lib install --git-url https://github.com/mathieucarbou/ESPAsyncWebServer#v2.10.0

      - name: Build Demo
        run: arduino-cli compile --library . --warnings all -b ${{ matrix.board }} "examples/demo/demo.ino"

      - name: Build Demo AP
        run: arduino-cli compile --library . --warnings all -b ${{ matrix.board }} "examples/demo_ap/demo_ap.ino"

  platformio:
    name: pio ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: esp32dev|arduino
            board: esp32dev
            platform: espressif32
            opts:
          - name: esp32dev|arduino-2
            board: esp32dev
            platform: espressif32@6.7.0
            opts:
          - name: esp32dev|arduino-3
            board: esp32dev
            platform: espressif32
            opts: "--project-option 'platform_packages=platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.0, platform_packages=platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.0/esp32-arduino-libs-3.0.0.zip'"

          - name: esp32-s3-devkitc-1|arduino
            board: esp32-s3-devkitc-1
            platform: espressif32
            opts:
          - name: esp32-s3-devkitc-1|arduino-2
            board: esp32-s3-devkitc-1
            platform: espressif32@6.7.0
            opts:
          - name: esp32-s3-devkitc-1|arduino-3
            board: esp32-s3-devkitc-1
            platform: espressif32
            opts: "--project-option 'platform_packages=platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.0, platform_packages=platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.0/esp32-arduino-libs-3.0.0.zip'"

    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
          key: ${{ matrix.name }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install platformio
      - run: platformio platform install ${{ matrix.platform }}
      - name: Build Demo
        run: platformio ci "examples/demo/demo.ino" -l '.' -b ${{ matrix.board }} ${{ matrix.opts }}
      - name: Build Demo AP
        run: platformio ci "examples/demo_ap/demo_ap.ino" -l '.' -b ${{ matrix.board }} ${{ matrix.opts }}
